[project]
name = "sp-project"
dynamic = ["version"]

[build-system]
requires = ["setuptools>=41", "setuptools-scm", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true