name: EntsoeActions

on:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * *"
jobs: 
  InsertWeatherDataToDB:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      OPENWEATHER_API_TOKEN: ${{ secrets.OPENWEATHER_API_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install .
      - run: python -m sp_project.data_collection.entsoe_scraper
