name: WeatherActions

on:
  workflow_dispatch:
  schedule:
    - cron: "55 14 * * *"
jobs: 
  InsertWeatherDataToDB:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install .
      - run: python -m sp_project.weather.db_updater
