name: Build and Deploy Webapp

on:
  push:
    branches:
      - 'main'

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build wheel
        run: |
          python -m pip install --user --upgrade build
          python -m build --wheel
      - uses: actions/upload-artifact@v3
        with:
          name: sp-project-wheel
          path: dist/

  docker:
    needs: build_wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sp-project-wheel
          path: dist/
      - run: |
          ls -al
          ls -al dist/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: '${{ secrets.GCP_ARTIFACT_PUSH }}'
          access_token_lifetime: 600s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: europe-north1-docker.pkg.dev/possible-coast-386219/docker/webserver:${{ github.sha }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: '${{ secrets.GCP_ARTIFACT_PUSH }}'
          access_token_lifetime: 600s

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: webserver
          region: europe-north1
          image: europe-north1-docker.pkg.dev/possible-coast-386219/docker/webserver:${{ github.sha }}

      - run: echo "WebApp deployed to ${{ steps.deploy.outputs.url }}"

